### PR TITLE
Fail process when at least one command fails

### PR DESCRIPTION
**Pull request by dalu93**
Hi orta,
Thank you very much for the great effort spent on this library. I just approached it and I immediately noticed that this very important issue (#7) needs to be fixed for my project. Hopefully you'll like how I solved it (in a fairly easy way, thou not elegant)

### CODE REVIEW

**Comment by orta** [comment]
Close! Nice shot

At the end you'll need to see if there are any fails and then call `exit(1)` which will mean git will stop also

**Comment by dalu93** [comment]
This should do that right?
```swift
guard failedCommands.isEmpty else {
    logger.logError("[Komondor] The following commands failed to execute: \(failedCommands.joined())")
    exit(1)
}
```

**Comment by daneov** [comment]
Anything I can do to help with this? 

Personally I think it'd be better to fail immediately when one fails, since they're executed synchronously and in order.

If we choose the other route and still execute all of them, I'd appreciate a 'failFast' flag 🤔

**Comment by orta** [comment]
Nah, should fail on the first - good point! Let's do that

**Comment by orta** [comment]
I'm afraid this got hit with a need to rebase

**Comment by dalu93** [comment]
I see that #10 fixes already this issue. Closing this PR

**Pull request closed without merging**
